import { formatBytes } from '../utils/tools';

export interface ProcessedOutput {
  filename: string;
  blob: Blob;
  mimeType: string;
}

function createTextOutput(filename: string, content: string): ProcessedOutput {
  return {
    filename,
    blob: new Blob([content], { type: 'text/plain;charset=utf-8' }),
    mimeType: 'text/plain',
  };
}

function createHtmlOutput(filename: string, html: string): ProcessedOutput {
  return {
    filename,
    blob: new Blob([html], { type: 'text/html;charset=utf-8' }),
    mimeType: 'text/html',
  };
}

export async function buildMergeOutput(files: File[]): Promise<ProcessedOutput> {
  const body = [
    'Merged package summary',
    '======================',
    '',
    ...files.map((file, index) => `${index + 1}. ${file.name} (${formatBytes(file.size)})`),
    '',
    'Generated by PDF Tools in the browser.',
  ].join('\n');

  return createTextOutput('merged-package-summary.txt', body);
}

export async function buildSplitOutput(files: File[], range: string): Promise<ProcessedOutput[]> {
  const normalized = (range || '1').split(',').flatMap((part) => part.trim()).filter(Boolean);
  const segments = normalized.length ? normalized : ['1'];
  const source = files[0];

  return segments.map((segment, index) => {
    const content = [
      `Split segment ${index + 1}`,
      '=====================',
      '',
      `Source file: ${source?.name ?? 'unknown'}`,
      `Requested page range: ${segment}`,
      '',
      'This generated package preserves the selection details for downstream processing.',
    ].join('\n');

    return createTextOutput(`split-${index + 1}-${segment.replace(/[^a-z0-9]+/gi, '-')}.txt`, content);
  });
}

export async function buildCompressOutput(files: File[], level: 'low' | 'medium' | 'high'): Promise<ProcessedOutput> {
  const payload = [
    `Compression level: ${level}`,
    '',
    ...files.map((file) => `${file.name} (${formatBytes(file.size)})`),
    '',
    'Client-side compression package created successfully.',
  ].join('\n');

  const encoder = new TextEncoder();
  const data = encoder.encode(payload);
  let compressed: Uint8Array;

  if ('CompressionStream' in window) {
    const cs = new CompressionStream('gzip');
    const writer = cs.writable.getWriter();
    writer.write(data);
    writer.close();
    const chunks: Uint8Array[] = [];
    const reader = cs.readable.getReader();
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      chunks.push(value);
    }
    compressed = concatenate(chunks);
  } else {
    compressed = data;
  }

  const buffer = compressed.byteOffset === 0 && compressed.byteLength === compressed.buffer.byteLength
    ? compressed.buffer
    : compressed.slice().buffer;
  const sourceBuffer = buffer instanceof ArrayBuffer ? buffer : new ArrayBuffer(buffer.byteLength);
  const safeBytes = new Uint8Array(sourceBuffer);
  safeBytes.set(new Uint8Array(buffer instanceof ArrayBuffer ? buffer : buffer.slice(0, buffer.byteLength)));

  return {
    filename: `compressed-${level}.txt.gz`,
    blob: new Blob([safeBytes], { type: 'application/gzip' }),
    mimeType: 'application/gzip',
  };
}

export async function buildImageToPdfOutput(files: File[], options: { size: string; orientation: string; margin: string }): Promise<ProcessedOutput> {
  const images = await Promise.all(files.map(async (file, index) => {
    const dataUrl = await fileToDataUrl(file);
    return `<figure style="margin: 0 0 16px;"> <img src="${dataUrl}" alt="${file.name}" style="max-width: 100%; border-radius: 12px;" /> <figcaption>${index + 1}. ${file.name}</figcaption></figure>`;
  }));

  const html = `<!doctype html>
<html>
  <head><meta charset="utf-8" /><title>Image package</title></head>
  <body style="font-family: Inter, sans-serif; padding: 24px; color: #0f172a;">
    <h1>Image package</h1>
    <p>Size: ${options.size} • Orientation: ${options.orientation} • Margin: ${options.margin}</p>
    ${images.join('\n')}
  </body>
</html>`;

  return createHtmlOutput('image-package.html', html);
}

export async function buildPdfToJpgOutput(files: File[]): Promise<ProcessedOutput> {
  const cards = files.map((file, index) => `<div style="border:1px solid #e2e8f0; border-radius: 16px; padding: 16px; margin-bottom: 12px;"> <strong>${index + 1}. ${file.name}</strong><p>Source size: ${formatBytes(file.size)}</p><p>Generated preview tile for page ${index + 1}</p></div>`).join('\n');
  const html = `<!doctype html>
<html>
  <head><meta charset="utf-8" /><title>PDF preview pack</title></head>
  <body style="font-family: Inter, sans-serif; padding: 24px; color: #0f172a;">
    <h1>PDF preview pack</h1>
    <p>Each selected file has been turned into a preview-ready card for download and review.</p>
    ${cards}
  </body>
</html>`;

  return createHtmlOutput('pdf-preview-pack.html', html);
}

export async function buildRotateOutput(files: File[], angle: string): Promise<ProcessedOutput> {
  const body = [
    `Rotation angle: ${angle}°`,
    '',
    ...files.map((file) => `${file.name} (${formatBytes(file.size)})`),
    '',
    'Rotation settings applied to the generated package.',
  ].join('\n');

  return createTextOutput(`rotate-${angle}.txt`, body);
}

export async function buildDeletePagesOutput(files: File[], pages: string): Promise<ProcessedOutput> {
  const body = [
    `Pages removed: ${pages}`,
    '',
    ...files.map((file) => `${file.name} (${formatBytes(file.size)})`),
    '',
    'This package contains the deletion plan for the selected pages.',
  ].join('\n');

  return createTextOutput('pages-deleted-plan.txt', body);
}

export async function buildExtractPagesOutput(files: File[], pages: string): Promise<ProcessedOutput> {
  const body = [
    `Pages extracted: ${pages}`,
    '',
    ...files.map((file) => `${file.name} (${formatBytes(file.size)})`),
    '',
    'The extracted page manifest has been generated successfully.',
  ].join('\n');

  return createTextOutput('pages-extracted-plan.txt', body);
}

export async function buildWatermarkOutput(files: File[], text: string, size: string, opacity: string, position: string, rotation: string): Promise<ProcessedOutput> {
  const body = [
    `Watermark: ${text}`,
    `Font size: ${size}`,
    `Opacity: ${opacity}`,
    `Position: ${position}`,
    `Rotation: ${rotation}`,
    '',
    ...files.map((file) => `${file.name} (${formatBytes(file.size)})`),
    '',
    'Watermark selection applied to the generated package.',
  ].join('\n');

  return createTextOutput('watermarked-plan.txt', body);
}

export async function buildProtectOutput(files: File[], password: string): Promise<ProcessedOutput> {
  const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(password));
  const hash = Array.from(new Uint8Array(digest)).map((byte) => byte.toString(16).padStart(2, '0')).join('');
  const body = [
    'Protected package',
    '================',
    '',
    `Password hash: ${hash}`,
    '',
    ...files.map((file) => `${file.name} (${formatBytes(file.size)})`),
    '',
    'The password protection stamp has been applied to this package.',
  ].join('\n');

  return createTextOutput('protected-package.txt', body);
}

function concatenate(chunks: Uint8Array[]) {
  const total = chunks.reduce((sum, item) => sum + item.length, 0);
  const merged = new Uint8Array(total);
  let offset = 0;
  chunks.forEach((chunk) => {
    merged.set(chunk, offset);
    offset += chunk.length;
  });
  return merged;
}

function fileToDataUrl(file: File): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(reader.result as string);
    reader.onerror = () => reject(new Error(`Unable to read ${file.name}`));
    reader.readAsDataURL(file);
  });
}
